.\" Voxelands man page
.TH "voxelands" "6" "1408.00" "Ye Myat Kaung 'Maverick' <mavjs@mavjs.org>" "Games"

.SH NAME
voxelands \- The Fun-Focused Free Software Voxel World Game

.SH SYNOPSIS
.B voxelands
[options]

.SH DESCRIPTION
.B Voxelands
is a sandbox construction game based on Minetest, which was Inspired by earlier "voxel world" games such as Infiniminer. Gameplay puts players in a fully destructible 3D game world where they can place and dig numerous types of blocks, items and creatures using a variety of tools. Inside the game world players can build structures, artworks and anything else their creativity can think of on multiplayer servers and singleplayer worlds across multiple game modes.

.SH OPTIONS
.TP
\-\--address <value>
Address to connect to
.TP
\-\--config <value>
Load configuration from specified file
.TP
\-\--disable-unittests
Disable unittests
.TP
\-\--enable-unittests
Enable unittests
.TP
\-\--help
Show allowed options
.TP
\-\--info-on-stderr
Print more information on standard error
.TP
\-\--map-dir <value>
Load map from specified directory
.TP
\-\--port <value>
Set network port (UDP) to use
.TP
\-\--random-input
Enable random user input, for testing
.TP
\-\--server
Run server directly
.TP
\-\--speedtests
Run speed tests

.SH BUGS
Please report all bugs at <http://forum.voxelands.com/>

.SH AUTHORS
.PP
Lisa 'darkrose' Milne <lisa@ltmnet.com>
and contributors: sdzen, MichaelEh?, Pentium44, Jordach, Menche, MavJS, tiemay.
.PP
This man page was written by
Ye Myat Kaung 'Maverick' <mavjs@mavjs.org> for the Voxelands community.

.SH WWW
http://voxelands.com

.SH "SEE ALSO"
.BR voxelandsserver(6)
