/************************************************************************
* content_toolitem.cpp
* voxelands - 3d voxel world sandbox game
* Copyright (C) Lisa Milne 2014 <lisa@ltmnet.com>
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>
************************************************************************/

#include "content_clothesitem.h"
#include "content_craftitem.h"
#include "content_craft.h"
#include "content_list.h"
#include "content_mapnode.h"
#include <map>
#include "gettext.h"

std::map<content_t,struct ClothesItemFeatures> g_content_clothesitem_features;

ClothesItemFeatures & content_clothesitem_features(content_t i)
{
	if ((i&CONTENT_CLOTHESITEM_MASK) != CONTENT_CLOTHESITEM_MASK)
		return g_content_clothesitem_features[CONTENT_IGNORE];

	std::map<content_t,struct ClothesItemFeatures>::iterator it = g_content_clothesitem_features.find(i);
	if (it == g_content_clothesitem_features.end())
		return g_content_clothesitem_features[CONTENT_IGNORE];
	return it->second;
}

void content_clothesitem_init()
{
	g_content_clothesitem_features.clear();

	content_t i;
	ClothesItemFeatures *f = NULL;

	i = CONTENT_CLOTHESITEM_SPACESUIT_PANTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->texture = "clothes_pants_space.png";
	f->overlay_texture = "clothes_player_pants_space.png";
	f->description = wgettext("Space Suit Pants");
	f->type = CT_PANTS;
	f->armour = 0.10;
	f->warmth = 0.20;
	f->vacuum = 0.30;
	f->durability = 20;
	{
		u16 r[9] = {
			CONTENT_CRAFTITEM_CANVAS_SHEET,	CONTENT_CRAFTITEM_CANVAS_SHEET,	CONTENT_CRAFTITEM_CANVAS_SHEET,
			CONTENT_CRAFTITEM_STEEL_INGOT,	CONTENT_IGNORE,			CONTENT_CRAFTITEM_STEEL_INGOT,
			CONTENT_CRAFTITEM_CANVAS_SHEET,	CONTENT_IGNORE,			CONTENT_CRAFTITEM_CANVAS_SHEET
		};
		crafting::setRecipe(r,i,1);
	}
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_SPACESUIT_SHIRT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->texture = "clothes_shirt_space.png";
	f->overlay_texture = "clothes_player_shirt_space.png";
	f->description = wgettext("Space Suit Shirt");
	f->type = CT_JACKET;
	f->armour = 0.10;
	f->warmth = 0.20;
	f->vacuum = 0.30;
	f->durability = 20;
	{
		u16 r[9] = {
			CONTENT_CRAFTITEM_CANVAS_SHEET,	CONTENT_CRAFTITEM_CANVAS_SHEET,	CONTENT_CRAFTITEM_CANVAS_SHEET,
			CONTENT_CRAFTITEM_STEEL_INGOT,	CONTENT_CRAFTITEM_CANVAS_SHEET,	CONTENT_CRAFTITEM_STEEL_INGOT,
			CONTENT_IGNORE,			CONTENT_CRAFTITEM_CANVAS_SHEET,	CONTENT_IGNORE
		};
		crafting::setRecipe(r,i,1);
	}
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_SPACESUIT_HELMET;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->texture = "clothes_helmet_space.png";
	f->overlay_texture = "clothes_player_helmet_space.png";
	f->description = wgettext("Space Suit Helmet");
	f->type = CT_HAT;
	f->armour = 0.05;
	f->warmth = 0.15;
	f->vacuum = 0.20;
	f->suffocate = 1.0;
	f->durability = 20;
	crafting::setHelmetRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_SPACESUIT_BOOTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->texture = "clothes_boots_space.png";
	f->overlay_texture = "clothes_player_boots_space.png";
	f->description = wgettext("Space Suit Boots");
	f->type = CT_BOOTS;
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.20;
	f->durability = 20;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// cotton t-shirts
	i = CONTENT_CLOTHESITEM_COTTON_TSHIRT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_tshirt_cotton_white.png";
	f->overlay_texture = "clothes_player_tshirt_cotton_white.png";
	f->description = wgettext("Cotton T-Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setTShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TSHIRT_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_tshirt_cotton_blue.png";
	f->overlay_texture = "clothes_player_tshirt_cotton_blue.png";
	f->description = wgettext("Blue Cotton T-Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setTShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TSHIRT_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_tshirt_cotton_green.png";
	f->overlay_texture = "clothes_player_tshirt_cotton_green.png";
	f->description = wgettext("Green Cotton T-Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setTShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TSHIRT_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_tshirt_cotton_orange.png";
	f->overlay_texture = "clothes_player_tshirt_cotton_orange.png";
	f->description = wgettext("Orange Cotton Tshirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setTShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TSHIRT_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_tshirt_cotton_purple.png";
	f->overlay_texture = "clothes_player_tshirt_cotton_purple.png";
	f->description = wgettext("Purple Cotton T-Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setTShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TSHIRT_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_tshirt_cotton_red.png";
	f->overlay_texture = "clothes_player_tshirt_cotton_red.png";
	f->description = wgettext("Red Cotton T-Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setTShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TSHIRT_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_tshirt_cotton_yellow.png";
	f->overlay_texture = "clothes_player_tshirt_cotton_yellow.png";
	f->description = wgettext("Yellow Cotton T-Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setTShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TSHIRT_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_tshirt_cotton_black.png";
	f->overlay_texture = "clothes_player_tshirt_cotton_black.png";
	f->description = wgettext("Black Cotton T-Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setTShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// cotton shirts
	i = CONTENT_CLOTHESITEM_COTTON_SHIRT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_cotton_white.png";
	f->overlay_texture = "clothes_player_shirt_cotton_white.png";
	f->description = wgettext("Cotton Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHIRT_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_cotton_blue.png";
	f->overlay_texture = "clothes_player_shirt_cotton_blue.png";
	f->description = wgettext("Blue Cotton Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHIRT_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_cotton_green.png";
	f->overlay_texture = "clothes_player_shirt_cotton_green.png";
	f->description = wgettext("Green Cotton Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHIRT_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_cotton_orange.png";
	f->overlay_texture = "clothes_player_shirt_cotton_orange.png";
	f->description = wgettext("Orange Cotton Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHIRT_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_cotton_purple.png";
	f->overlay_texture = "clothes_player_shirt_cotton_purple.png";
	f->description = wgettext("Purple Cotton Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHIRT_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_cotton_red.png";
	f->overlay_texture = "clothes_player_shirt_cotton_red.png";
	f->description = wgettext("Red Cotton Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHIRT_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_cotton_yellow.png";
	f->overlay_texture = "clothes_player_shirt_cotton_yellow.png";
	f->description = wgettext("Yellow Cotton Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHIRT_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_cotton_black.png";
	f->overlay_texture = "clothes_player_shirt_cotton_black.png";
	f->description = wgettext("Black Cotton Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// cotton shorts
	i = CONTENT_CLOTHESITEM_COTTON_SHORTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_shorts_cotton_white.png";
	f->overlay_texture = "clothes_player_shorts_cotton_white.png";
	f->description = wgettext("Cotton Shorts");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShortsRecipe(CONTENT_CRAFTITEM_COTTON_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHORTS_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_shorts_cotton_blue.png";
	f->overlay_texture = "clothes_player_shorts_cotton_blue.png";
	f->description = wgettext("Blue Cotton Shorts");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShortsRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHORTS_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_shorts_cotton_green.png";
	f->overlay_texture = "clothes_player_shorts_cotton_green.png";
	f->description = wgettext("Green Cotton Shorts");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShortsRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHORTS_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_shorts_cotton_orange.png";
	f->overlay_texture = "clothes_player_shorts_cotton_orange.png";
	f->description = wgettext("Orange Cotton Shorts");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShortsRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHORTS_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_shorts_cotton_purple.png";
	f->overlay_texture = "clothes_player_shorts_cotton_purple.png";
	f->description = wgettext("Purple Cotton Shorts");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShortsRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHORTS_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_shorts_cotton_red.png";
	f->overlay_texture = "clothes_player_shorts_cotton_red.png";
	f->description = wgettext("Red Cotton Shorts");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShortsRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHORTS_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_shorts_cotton_yellow.png";
	f->overlay_texture = "clothes_player_shorts_cotton_yellow.png";
	f->description = wgettext("Yellow Cotton Shorts");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShortsRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_SHORTS_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_shorts_cotton_black.png";
	f->overlay_texture = "clothes_player_shorts_cotton_black.png";
	f->description = wgettext("Black Cotton Shorts");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShortsRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// cotton hats
	i = CONTENT_CLOTHESITEM_COTTON_HAT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_cotton_white.png";
	f->overlay_texture = "clothes_player_hat_cotton_white.png";
	f->description = wgettext("Cotton Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_COTTON_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_HAT_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_cotton_blue.png";
	f->overlay_texture = "clothes_player_hat_cotton_blue.png";
	f->description = wgettext("Blue Cotton Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_HAT_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_cotton_green.png";
	f->overlay_texture = "clothes_player_hat_cotton_green.png";
	f->description = wgettext("Green Cotton Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_HAT_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_cotton_orange.png";
	f->overlay_texture = "clothes_player_hat_cotton_orange.png";
	f->description = wgettext("Orange Cotton Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_HAT_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_cotton_purple.png";
	f->overlay_texture = "clothes_player_hat_cotton_purple.png";
	f->description = wgettext("Purple Cotton Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_HAT_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_cotton_red.png";
	f->overlay_texture = "clothes_player_hat_cotton_red.png";
	f->description = wgettext("Red Cotton Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_HAT_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_cotton_yellow.png";
	f->overlay_texture = "clothes_player_hat_cotton_yellow.png";
	f->description = wgettext("Yellow Cotton Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_HAT_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_cotton_black.png";
	f->overlay_texture = "clothes_player_hat_cotton_blacK.png";
	f->description = wgettext("Black Cotton Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_COTTON_SHEET_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// cotton ties
	i = CONTENT_CLOTHESITEM_COTTON_TIE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_DECORATIVE;
	f->texture = "clothes_tie_cotton_white.png";
	f->overlay_texture = "clothes_player_tie_cotton_white.png";
	f->description = wgettext("Cotton Tie");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CRAFTITEM_COTTON_SHEET,CONTENT_CRAFTITEM_COTTON_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TIE_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_DECORATIVE;
	f->texture = "clothes_tie_cotton_blue.png";
	f->overlay_texture = "clothes_player_tie_cotton_blue.png";
	f->description = wgettext("Blue Cotton Tie");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CRAFTITEM_COTTON_SHEET_BLUE,CONTENT_CRAFTITEM_COTTON_SHEET_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TIE_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_DECORATIVE;
	f->texture = "clothes_tie_cotton_green.png";
	f->overlay_texture = "clothes_player_tie_cotton_green.png";
	f->description = wgettext("Green Cotton Tie");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CRAFTITEM_COTTON_SHEET_GREEN,CONTENT_CRAFTITEM_COTTON_SHEET_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TIE_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_DECORATIVE;
	f->texture = "clothes_tie_cotton_orange.png";
	f->overlay_texture = "clothes_player_tie_cotton_orange.png";
	f->description = wgettext("Orange Cotton Tie");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CRAFTITEM_COTTON_SHEET_ORANGE,CONTENT_CRAFTITEM_COTTON_SHEET_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TIE_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_DECORATIVE;
	f->texture = "clothes_tie_cotton_purple.png";
	f->overlay_texture = "clothes_player_tie_cotton_purple.png";
	f->description = wgettext("Purple Cotton Tie");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CRAFTITEM_COTTON_SHEET_PURPLE,CONTENT_CRAFTITEM_COTTON_SHEET_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TIE_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_DECORATIVE;
	f->texture = "clothes_tie_cotton_red.png";
	f->overlay_texture = "clothes_player_tie_cotton_red.png";
	f->description = wgettext("Red Cotton Tie");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CRAFTITEM_COTTON_SHEET_RED,CONTENT_CRAFTITEM_COTTON_SHEET_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TIE_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_DECORATIVE;
	f->texture = "clothes_tie_cotton_yellow.png";
	f->overlay_texture = "clothes_player_tie_cotton_yellow.png";
	f->description = wgettext("Yellow Cotton Tie");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CRAFTITEM_COTTON_SHEET_YELLOW,CONTENT_CRAFTITEM_COTTON_SHEET_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COTTON_TIE_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_DECORATIVE;
	f->texture = "clothes_tie_cotton_black.png";
	f->overlay_texture = "clothes_player_tie_cotton_black.png";
	f->description = wgettext("Black Cotton Tie");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CRAFTITEM_COTTON_SHEET_BLACK,CONTENT_CRAFTITEM_COTTON_SHEET_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// canvas shirt - jacket?
	i = CONTENT_CLOTHESITEM_CANVAS_SHIRT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_canvas_white.png";
	f->overlay_texture = "clothes_player_shirt_canvas_white.png";
	f->description = wgettext("Canvas Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHIRT_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_canvas_blue.png";
	f->overlay_texture = "clothes_player_shirt_canvas_blue.png";
	f->description = wgettext("Blue Canvas Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHIRT_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_canvas_green.png";
	f->overlay_texture = "clothes_player_shirt_canvas_green.png";
	f->description = wgettext("Green Canvas Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHIRT_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_canvas_orange.png";
	f->overlay_texture = "clothes_player_shirt_canvas_orange.png";
	f->description = wgettext("Orange Canvas Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHIRT_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_canvas_purple.png";
	f->overlay_texture = "clothes_player_shirt_canvas_purple.png";
	f->description = wgettext("Purple Canvas Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHIRT_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_canvas_red.png";
	f->overlay_texture = "clothes_player_shirt_canvas_red.png";
	f->description = wgettext("Red Canvas Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHIRT_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_canvas_yellow.png";
	f->overlay_texture = "clothes_player_shirt_canvas_yellow.png";
	f->description = wgettext("Yellow Canvas Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHIRT_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_SHIRT;
	f->texture = "clothes_shirt_canvas_black.png";
	f->overlay_texture = "clothes_player_shirt_canvas_black.png";
	f->description = wgettext("Black Canvas Shirt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// canvas pants / jeans
	i = CONTENT_CLOTHESITEM_CANVAS_PANTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_canvas_white.png";
	f->overlay_texture = "clothes_player_pants_canvas_white.png";
	f->description = wgettext("Canvas Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_PANTS_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_canvas_blue.png";
	f->overlay_texture = "clothes_player_pants_canvas_blue.png";
	f->description = wgettext("Blue Canvas Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_PANTS_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_canvas_green.png";
	f->overlay_texture = "clothes_player_pants_canvas_green.png";
	f->description = wgettext("Green Canvas Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_PANTS_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_canvas_orange.png";
	f->overlay_texture = "clothes_player_pants_canvas_orange.png";
	f->description = wgettext("Orange Canvas Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_PANTS_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_canvas_purple.png";
	f->overlay_texture = "clothes_player_pants_canvas_purple.png";
	f->description = wgettext("Purple Canvas Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_PANTS_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_canvas_red.png";
	f->overlay_texture = "clothes_player_pants_canvas_red.png";
	f->description = wgettext("Red Canvas Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_PANTS_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_canvas_yellow.png";
	f->overlay_texture = "clothes_player_pants_canvas_yellow.png";
	f->description = wgettext("Yellow Canvas Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_PANTS_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_canvas_black.png";
	f->overlay_texture = "clothes_player_pants_canvas_black.png";
	f->description = wgettext("Black Canvas Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// canvas shoes
	i = CONTENT_CLOTHESITEM_CANVAS_SHOES;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_canvas_white.png";
	f->overlay_texture = "clothes_player_shoes_canvas_white.png";
	f->description = wgettext("Canvas Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHOES_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_canvas_blue.png";
	f->overlay_texture = "clothes_player_shoes_canvas_blue.png";
	f->description = wgettext("Blue Canvas Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHOES_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_canvas_green.png";
	f->overlay_texture = "clothes_player_shoes_canvas_green.png";
	f->description = wgettext("Green Canvas Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHOES_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_canvas_orange.png";
	f->overlay_texture = "clothes_player_shoes_canvas_orange.png";
	f->description = wgettext("Orange Canvas Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHOES_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_canvas_purple.png";
	f->overlay_texture = "clothes_player_shoes_canvas_purple.png";
	f->description = wgettext("Purple Canvas Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHOES_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_canvas_red.png";
	f->overlay_texture = "clothes_player_shoes_canvas_red.png";
	f->description = wgettext("Red Canvas Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHOES_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_canvas_yellow.png";
	f->overlay_texture = "clothes_player_shoes_canvas_yellow.png";
	f->description = wgettext("Yellow Canvas Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_SHOES_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_canvas_black.png";
	f->overlay_texture = "clothes_player_shoes_canvas_black.png";
	f->description = wgettext("Black Canvas Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_CANVAS_SHEET_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// canvas belt
	i = CONTENT_CLOTHESITEM_CANVAS_BELT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_canvas_white.png";
	f->overlay_texture = "clothes_player_belt_canvas_white.png";
	f->description = wgettext("Canvas Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_CANVAS_SHEET,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_BELT_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_canvas_blue.png";
	f->overlay_texture = "clothes_player_belt_canvas_blue.png";
	f->description = wgettext("Blue Canvas Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_CANVAS_SHEET_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_BELT_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_canvas_green.png";
	f->overlay_texture = "clothes_player_belt_canvas_green.png";
	f->description = wgettext("Green Canvas Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_CANVAS_SHEET_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_BELT_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_canvas_orange.png";
	f->overlay_texture = "clothes_player_belt_canvas_orange.png";
	f->description = wgettext("Orange Canvas Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_CANVAS_SHEET_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_BELT_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_canvas_purple.png";
	f->overlay_texture = "clothes_player_belt_canvas_purple.png";
	f->description = wgettext("Purple Canvas Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_CANVAS_SHEET_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_BELT_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_canvas_red.png";
	f->overlay_texture = "clothes_player_belt_canvas_red.png";
	f->description = wgettext("Red Canvas Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_CANVAS_SHEET_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_BELT_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_canvas_yellow.png";
	f->overlay_texture = "clothes_player_belt_canvas_yellow.png";
	f->description = wgettext("Yellow Canvas Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_CANVAS_SHEET_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_CANVAS_BELT_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_canvas_black.png";
	f->overlay_texture = "clothes_player_belt_canvas_black.png";
	f->description = wgettext("Black Canvas Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_CANVAS_SHEET_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// leather shirts
	i = CONTENT_CLOTHESITEM_LEATHER_JACKET;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_leather_brown.png";
	f->overlay_texture = "clothes_player_jacket_leather_brown.png";
	f->description = wgettext("Leather Jacket");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_LEATHER,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_JACKET_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_leather_white.png";
	f->overlay_texture = "clothes_player_jacket_leather_white.png";
	f->description = wgettext("White Leather Jacket");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_LEATHER_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_JACKET_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_leather_blue.png";
	f->overlay_texture = "clothes_player_jacket_leather_blue.png";
	f->description = wgettext("Blue Leather Jacket");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_LEATHER_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_JACKET_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_leather_green.png";
	f->overlay_texture = "clothes_player_jacket_leather_green.png";
	f->description = wgettext("Green Leather Jacket");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_LEATHER_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_JACKET_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_leather_orange.png";
	f->overlay_texture = "clothes_player_jacket_leather_orange.png";
	f->description = wgettext("Orange Leather Jacket");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_LEATHER_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_JACKET_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_leather_purple.png";
	f->overlay_texture = "clothes_player_jacket_leather_purple.png";
	f->description = wgettext("Purple Leather Jacket");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_LEATHER_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_JACKET_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_leather_red.png";
	f->overlay_texture = "clothes_player_jacket_leather_red.png";
	f->description = wgettext("Red Leather Jacket");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_LEATHER_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_JACKET_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_leather_yellow.png";
	f->overlay_texture = "clothes_player_jacket_leather_yellow.png";
	f->description = wgettext("Yellow Leather Jacket");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_LEATHER_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_JACKET_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_leather_black.png";
	f->overlay_texture = "clothes_player_jacket_leather_black.png";
	f->description = wgettext("Black Leather Jacket");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_LEATHER_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// leather pants
	i = CONTENT_CLOTHESITEM_LEATHER_PANTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_leather_brown.png";
	f->overlay_texture = "clothes_player_pants_leather_brown.png";
	f->description = wgettext("Leather Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_LEATHER,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_PANTS_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_leather_white.png";
	f->overlay_texture = "clothes_player_pants_leather_white.png";
	f->description = wgettext("White Leather Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_LEATHER_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_PANTS_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_leather_blue.png";
	f->overlay_texture = "clothes_player_pants_leather_blue.png";
	f->description = wgettext("Blue Leather Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_LEATHER_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_PANTS_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_leather_green.png";
	f->overlay_texture = "clothes_player_pants_leather_green.png";
	f->description = wgettext("Green Leather Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_LEATHER_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_PANTS_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_leather_orange.png";
	f->overlay_texture = "clothes_player_pants_leather_orange.png";
	f->description = wgettext("Orange Leather Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_LEATHER_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_PANTS_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_leather_purple.png";
	f->overlay_texture = "clothes_player_pants_leather_purple.png";
	f->description = wgettext("Purple Leather Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_LEATHER_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_PANTS_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_leather_red.png";
	f->overlay_texture = "clothes_player_pants_leather_red.png";
	f->description = wgettext("Red Leather Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_LEATHER_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_PANTS_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_leather_yellow.png";
	f->overlay_texture = "clothes_player_pants_leather_yellow.png";
	f->description = wgettext("Yellow Leather Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_LEATHER_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_PANTS_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_leather_black.png";
	f->overlay_texture = "clothes_player_pants_leather_black.png";
	f->description = wgettext("Black Leather Pants");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_LEATHER_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// leather hats
	i = CONTENT_CLOTHESITEM_LEATHER_HAT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_leather_brown.png";
	f->overlay_texture = "clothes_player_hat_leather_brown.png";
	f->description = wgettext("Leather Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_LEATHER,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HAT_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_leather_white.png";
	f->overlay_texture = "clothes_player_hat_leather_white.png";
	f->description = wgettext("White Leather Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_LEATHER_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HAT_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_leather_blue.png";
	f->overlay_texture = "clothes_player_hat_leather_blue.png";
	f->description = wgettext("Blue Leather Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_LEATHER_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HAT_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_leather_green.png";
	f->overlay_texture = "clothes_player_hat_leather_green.png";
	f->description = wgettext("Green Leather Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_LEATHER_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HAT_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_leather_orange.png";
	f->overlay_texture = "clothes_player_hat_leather_orange.png";
	f->description = wgettext("Orange Leather Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_LEATHER_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HAT_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_leather_purple.png";
	f->overlay_texture = "clothes_player_hat_leather_purple.png";
	f->description = wgettext("Purple Leather Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_LEATHER_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HAT_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_leather_red.png";
	f->overlay_texture = "clothes_player_hat_leather_red.png";
	f->description = wgettext("Red Leather Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_LEATHER_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HAT_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_leather_yellow.png";
	f->overlay_texture = "clothes_player_hat_leather_yellow.png";
	f->description = wgettext("Yellow Leather Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_LEATHER_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HAT_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_leather_black.png";
	f->overlay_texture = "clothes_player_hat_leather_black.png";
	f->description = wgettext("Black Leather Hat");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_LEATHER_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// leather helmets
	i = CONTENT_CLOTHESITEM_LEATHER_HELMET;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_leather_brown.png";
	f->overlay_texture = "clothes_player_helmet_leather_brown.png";
	f->description = wgettext("Leather Helmet");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHelmetRecipe(CONTENT_CRAFTITEM_LEATHER,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HELMET_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_leather_white.png";
	f->overlay_texture = "clothes_player_helmet_leather_white.png";
	f->description = wgettext("White Leather Helmet");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHelmetRecipe(CONTENT_CRAFTITEM_LEATHER_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HELMET_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_leather_blue.png";
	f->overlay_texture = "clothes_player_helmet_leather_blue.png";
	f->description = wgettext("Blue Leather Helmet");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHelmetRecipe(CONTENT_CRAFTITEM_LEATHER_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HELMET_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_leather_green.png";
	f->overlay_texture = "clothes_player_helmet_leather_green.png";
	f->description = wgettext("Green Leather Helmet");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHelmetRecipe(CONTENT_CRAFTITEM_LEATHER_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HELMET_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_leather_orange.png";
	f->overlay_texture = "clothes_player_helmet_leather_orange.png";
	f->description = wgettext("Orange Leather Helmet");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHelmetRecipe(CONTENT_CRAFTITEM_LEATHER_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HELMET_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_leather_purple.png";
	f->overlay_texture = "clothes_player_helmet_leather_purple.png";
	f->description = wgettext("Purple Leather Helmet");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHelmetRecipe(CONTENT_CRAFTITEM_LEATHER_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HELMET_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_leather_red.png";
	f->overlay_texture = "clothes_player_helmet_leather_red.png";
	f->description = wgettext("Red Leather Helmet");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHelmetRecipe(CONTENT_CRAFTITEM_LEATHER_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HELMET_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_leather_yellow.png";
	f->overlay_texture = "clothes_player_helmet_leather_yellow.png";
	f->description = wgettext("Yellow Leather Helmet");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHelmetRecipe(CONTENT_CRAFTITEM_LEATHER_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_HELMET_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_leather_black.png";
	f->overlay_texture = "clothes_player_helmet_leather_black.png";
	f->description = wgettext("Black Leather Helmet");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHelmetRecipe(CONTENT_CRAFTITEM_LEATHER_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// leather shoes
	i = CONTENT_CLOTHESITEM_LEATHER_SHOES;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_leather_brown.png";
	f->overlay_texture = "clothes_player_shoes_leather_brown.png";
	f->description = wgettext("Leather Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_LEATHER,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_SHOES_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_leather_white.png";
	f->overlay_texture = "clothes_player_shoes_leather_white.png";
	f->description = wgettext("White Leather Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_LEATHER_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_SHOES_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_leather_blue.png";
	f->overlay_texture = "clothes_player_shoes_leather_blue.png";
	f->description = wgettext("Blue Leather Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_LEATHER_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_SHOES_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_leather_green.png";
	f->overlay_texture = "clothes_player_shoes_leather_green.png";
	f->description = wgettext("Green Leather Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_LEATHER_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_SHOES_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_leather_orange.png";
	f->overlay_texture = "clothes_player_shoes_leather_orange.png";
	f->description = wgettext("Orange Leather Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_LEATHER_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_SHOES_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_leather_purple.png";
	f->overlay_texture = "clothes_player_shoes_leather_purple.png";
	f->description = wgettext("Purple Leather Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_LEATHER_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_SHOES_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_leather_red.png";
	f->overlay_texture = "clothes_player_shoes_leather_red.png";
	f->description = wgettext("Red Leather Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_LEATHER_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_SHOES_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_leather_yellow.png";
	f->overlay_texture = "clothes_player_shoes_leather_yellow.png";
	f->description = wgettext("Yellow Leather Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_LEATHER_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_SHOES_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_leather_black.png";
	f->overlay_texture = "clothes_player_shoes_leather_black.png";
	f->description = wgettext("Black Leather Shoes");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_LEATHER_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// leather boots
	i = CONTENT_CLOTHESITEM_LEATHER_BOOTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_leather_brown.png";
	f->overlay_texture = "clothes_player_boots_leather_brown.png";
	f->description = wgettext("Leather Boots");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_LEATHER,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BOOTS_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_leather_white.png";
	f->overlay_texture = "clothes_player_boots_leather_white.png";
	f->description = wgettext("White Leather Boots");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_LEATHER_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BOOTS_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_leather_blue.png";
	f->overlay_texture = "clothes_player_boots_leather_blue.png";
	f->description = wgettext("Blue Leather Boots");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_LEATHER_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BOOTS_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_leather_green.png";
	f->overlay_texture = "clothes_player_boots_leather_green.png";
	f->description = wgettext("Green Leather Boots");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_LEATHER_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BOOTS_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_leather_orange.png";
	f->overlay_texture = "clothes_player_boots_leather_orange.png";
	f->description = wgettext("Orange Leather Boots");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_LEATHER_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BOOTS_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_leather_purple.png";
	f->overlay_texture = "clothes_player_boots_leather_purple.png";
	f->description = wgettext("Purple Leather Boots");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_LEATHER_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BOOTS_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_leather_red.png";
	f->overlay_texture = "clothes_player_boots_leather_red.png";
	f->description = wgettext("Red Leather Boots");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_LEATHER_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BOOTS_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_leather_yellow.png";
	f->overlay_texture = "clothes_player_boots_leather_yellow.png";
	f->description = wgettext("Yellow Leather Boots");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_LEATHER_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BOOTS_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_leather_black.png";
	f->overlay_texture = "clothes_player_boots_leather_black.png";
	f->description = wgettext("Black Leather Boots");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_LEATHER_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// leather belt
	i = CONTENT_CLOTHESITEM_LEATHER_BELT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_leather_brown.png";
	f->overlay_texture = "clothes_player_belt_leather_brown.png";
	f->description = wgettext("Leather Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_LEATHER,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BELT_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_leather_white.png";
	f->overlay_texture = "clothes_player_belt_leather_white.png";
	f->description = wgettext("White Leather Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_LEATHER_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BELT_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_leather_blue.png";
	f->overlay_texture = "clothes_player_belt_leather_blue.png";
	f->description = wgettext("Blue Leather Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_LEATHER_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BELT_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_leather_green.png";
	f->overlay_texture = "clothes_player_belt_leather_green.png";
	f->description = wgettext("Green Leather Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_LEATHER_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BELT_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_leather_orange.png";
	f->overlay_texture = "clothes_player_belt_leather_orange.png";
	f->description = wgettext("Orange Leather Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_LEATHER_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BELT_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_leather_purple.png";
	f->overlay_texture = "clothes_player_belt_leather_purple.png";
	f->description = wgettext("Purple Leather Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_LEATHER_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BELT_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_leather_red.png";
	f->overlay_texture = "clothes_player_belt_leather_red.png";
	f->description = wgettext("Red Leather Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_LEATHER_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BELT_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_leather_yellow.png";
	f->overlay_texture = "clothes_player_belt_leather_yellow.png";
	f->description = wgettext("Yellow Leather Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_LEATHER_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_LEATHER_BELT_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BELT;
	f->texture = "clothes_belt_leather_black.png";
	f->overlay_texture = "clothes_player_belt_leather_black.png";
	f->description = wgettext("Black Leather Belt");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setRow1Recipe(CONTENT_CRAFTITEM_LEATHER_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// fur shirts
	i = CONTENT_CLOTHESITEM_FUR_JACKET;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_fur_brown.png";
	f->overlay_texture = "clothes_player_jacket_fur_brown.png";
	f->description = wgettext("Fur Coat");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_FUR,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_JACKET_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_fur_white.png";
	f->overlay_texture = "clothes_player_jacket_fur_white.png";
	f->description = wgettext("White Fur Coat");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_FUR_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_JACKET_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_fur_blue.png";
	f->overlay_texture = "clothes_player_jacket_fur_blue.png";
	f->description = wgettext("Blue Fur Coat");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_FUR_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_JACKET_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_fur_green.png";
	f->overlay_texture = "clothes_player_jacket_fur_green.png";
	f->description = wgettext("Green Fur Coat");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_FUR_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_JACKET_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_fur_orange.png";
	f->overlay_texture = "clothes_player_jacket_fur_orange.png";
	f->description = wgettext("Orange Fur Coat");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_FUR_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_JACKET_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_fur_purple.png";
	f->overlay_texture = "clothes_player_jacket_fur_purple.png";
	f->description = wgettext("Purple Fur Coat");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_FUR_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_JACKET_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_fur_red.png";
	f->overlay_texture = "clothes_player_jacket_fur_red.png";
	f->description = wgettext("Red Fur Coat");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_FUR_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_JACKET_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_fur_yellow.png";
	f->overlay_texture = "clothes_player_jacket_fur_yellow.png";
	f->description = wgettext("Yellow Fur Coat");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_FUR_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_JACKET_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_jacket_fur_black.png";
	f->overlay_texture = "clothes_player_jacket_fur_black.png";
	f->description = wgettext("Black Fur Coat");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_FUR_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// fur pants
	i = CONTENT_CLOTHESITEM_FUR_PANTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_fur_brown.png";
	f->overlay_texture = "clothes_player_pants_fur_brown.png";
	f->description = wgettext("Fur Pants");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_FUR,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_PANTS_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_fur_white.png";
	f->overlay_texture = "clothes_player_pants_fur_white.png";
	f->description = wgettext("White Fur Pants");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_FUR_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_PANTS_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_fur_blue.png";
	f->overlay_texture = "clothes_player_pants_fur_blue.png";
	f->description = wgettext("Blue Fur Pants");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_FUR_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_PANTS_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_fur_green.png";
	f->overlay_texture = "clothes_player_pants_fur_green.png";
	f->description = wgettext("Green Fur Pants");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_FUR_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_PANTS_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_fur_orange.png";
	f->overlay_texture = "clothes_player_pants_fur_orange.png";
	f->description = wgettext("Orange Fur Pants");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_FUR_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_PANTS_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_fur_purple.png";
	f->overlay_texture = "clothes_player_pants_fur_purple.png";
	f->description = wgettext("Purple Fur Pants");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_FUR_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_PANTS_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_fur_red.png";
	f->overlay_texture = "clothes_player_pants_fur_red.png";
	f->description = wgettext("Red Fur Pants");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_FUR_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_PANTS_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_fur_yellow.png";
	f->overlay_texture = "clothes_player_pants_fur_yellow.png";
	f->description = wgettext("Yellow Fur Pants");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_FUR_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_PANTS_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_fur_black.png";
	f->overlay_texture = "clothes_player_pants_fur_black.png";
	f->description = wgettext("Black Fur Pants");
	f->armour = 0.10;
	f->warmth = 0.30;
	f->vacuum = 0.05;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_FUR_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// fur hats
	i = CONTENT_CLOTHESITEM_FUR_HAT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_fur_brown.png";
	f->overlay_texture = "clothes_player_hat_fur_brown.png";
	f->description = wgettext("Fur Hat");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_FUR,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_HAT_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_fur_white.png";
	f->overlay_texture = "clothes_player_hat_fur_white.png";
	f->description = wgettext("White Fur Hat");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_FUR_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_HAT_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_fur_blue.png";
	f->overlay_texture = "clothes_player_hat_fur_blue.png";
	f->description = wgettext("Blue Fur Hat");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_FUR_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_HAT_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_fur_green.png";
	f->overlay_texture = "clothes_player_hat_fur_green.png";
	f->description = wgettext("Green Fur Hat");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_FUR_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_HAT_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_fur_orange.png";
	f->overlay_texture = "clothes_player_hat_fur_orange.png";
	f->description = wgettext("Orange Fur Hat");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_FUR_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_HAT_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_fur_purple.png";
	f->overlay_texture = "clothes_player_hat_fur_purple.png";
	f->description = wgettext("Purple Fur Hat");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_FUR_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_HAT_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_fur_red.png";
	f->overlay_texture = "clothes_player_hat_fur_red.png";
	f->description = wgettext("Red Fur Hat");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_FUR_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_HAT_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_fur_yellow.png";
	f->overlay_texture = "clothes_player_hat_fur_yellow.png";
	f->description = wgettext("Yellow Fur Hat");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_FUR_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_HAT_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_hat_fur_black.png";
	f->overlay_texture = "clothes_player_hat_fur_black.png";
	f->description = wgettext("Black Fur Hat");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_FUR_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// fur shoes
	i = CONTENT_CLOTHESITEM_FUR_SHOES;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_fur_brown.png";
	f->overlay_texture = "clothes_player_shoes_fur_brown.png";
	f->description = wgettext("Fur Shoes");
	f->armour = 0.05;
	f->warmth = 0.10;
	f->vacuum = 0.05;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_FUR,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_SHOES_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_fur_white.png";
	f->overlay_texture = "clothes_player_shoes_fur_white.png";
	f->description = wgettext("White Fur Shoes");
	f->armour = 0.05;
	f->warmth = 0.10;
	f->vacuum = 0.05;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_FUR_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_SHOES_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_fur_blue.png";
	f->overlay_texture = "clothes_player_shoes_fur_blue.png";
	f->description = wgettext("Blue Fur Shoes");
	f->armour = 0.05;
	f->warmth = 0.10;
	f->vacuum = 0.05;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_FUR_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_SHOES_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_fur_green.png";
	f->overlay_texture = "clothes_player_shoes_fur_green.png";
	f->description = wgettext("Green Fur Shoes");
	f->armour = 0.05;
	f->warmth = 0.10;
	f->vacuum = 0.05;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_FUR_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_SHOES_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_fur_orange.png";
	f->overlay_texture = "clothes_player_shoes_fur_orange.png";
	f->description = wgettext("Orange Fur Shoes");
	f->armour = 0.05;
	f->warmth = 0.10;
	f->vacuum = 0.05;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_FUR_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_SHOES_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_fur_purple.png";
	f->overlay_texture = "clothes_player_shoes_fur_purple.png";
	f->description = wgettext("Purple Fur Shoes");
	f->armour = 0.05;
	f->warmth = 0.10;
	f->vacuum = 0.05;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_FUR_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_SHOES_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_fur_red.png";
	f->overlay_texture = "clothes_player_shoes_fur_red.png";
	f->description = wgettext("Red Fur Shoes");
	f->armour = 0.05;
	f->warmth = 0.10;
	f->vacuum = 0.05;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_FUR_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_SHOES_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_fur_yellow.png";
	f->overlay_texture = "clothes_player_shoes_fur_yellow.png";
	f->description = wgettext("Yellow Fur Shoes");
	f->armour = 0.05;
	f->warmth = 0.10;
	f->vacuum = 0.05;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_FUR_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_SHOES_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_shoes_fur_black.png";
	f->overlay_texture = "clothes_player_shoes_fur_black.png";
	f->description = wgettext("Black Fur Shoes");
	f->armour = 0.05;
	f->warmth = 0.10;
	f->vacuum = 0.05;
	crafting::setShoesRecipe(CONTENT_CRAFTITEM_FUR_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// fur boots
	i = CONTENT_CLOTHESITEM_FUR_BOOTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_fur_brown.png";
	f->overlay_texture = "clothes_player_boots_fur_brown.png";
	f->description = wgettext("Fur Boots");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_FUR,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_BOOTS_WHITE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_fur_white.png";
	f->overlay_texture = "clothes_player_boots_fur_white.png";
	f->description = wgettext("White Fur Boots");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_FUR_WHITE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_BOOTS_BLUE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_fur_blue.png";
	f->overlay_texture = "clothes_player_boots_fur_blue.png";
	f->description = wgettext("Blue Fur Boots");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_FUR_BLUE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_BOOTS_GREEN;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_fur_green.png";
	f->overlay_texture = "clothes_player_boots_fur_green.png";
	f->description = wgettext("Green Fur Boots");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_FUR_GREEN,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_BOOTS_ORANGE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_fur_orange.png";
	f->overlay_texture = "clothes_player_boots_fur_orange.png";
	f->description = wgettext("Orange Fur Boots");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_FUR_ORANGE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_BOOTS_PURPLE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_fur_purple.png";
	f->overlay_texture = "clothes_player_boots_fur_purple.png";
	f->description = wgettext("Purple Fur Boots");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_FUR_PURPLE,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_BOOTS_RED;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_fur_red.png";
	f->overlay_texture = "clothes_player_boots_fur_red.png";
	f->description = wgettext("Red Fur Boots");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_FUR_RED,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_BOOTS_YELLOW;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_fur_yellow.png";
	f->overlay_texture = "clothes_player_boots_fur_yellow.png";
	f->description = wgettext("Yellow Fur Boots");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_FUR_YELLOW,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_FUR_BOOTS_BLACK;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_fur_black.png";
	f->overlay_texture = "clothes_player_boots_fur_black.png";
	f->description = wgettext("Black Fur Boots");
	f->armour = 0.05;
	f->warmth = 0.20;
	f->vacuum = 0.05;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_FUR_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// necklaces / medallions
	i = CONTENT_CLOTHESITEM_LEATHER_NECKLACE;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_DECORATIVE;
	f->texture = "clothes_necklace_leather.png";
	f->overlay_texture = "clothes_player_necklace_leather.png";
	f->description = wgettext("Leather Necklace");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1To1Recipe(CONTENT_CRAFTITEM_LEATHER,i);
	crafting::set1To1Recipe(CONTENT_CRAFTITEM_LEATHER_WHITE,i);
	crafting::set1To1Recipe(CONTENT_CRAFTITEM_LEATHER_BLUE,i);
	crafting::set1To1Recipe(CONTENT_CRAFTITEM_LEATHER_GREEN,i);
	crafting::set1To1Recipe(CONTENT_CRAFTITEM_LEATHER_ORANGE,i);
	crafting::set1To1Recipe(CONTENT_CRAFTITEM_LEATHER_PURPLE,i);
	crafting::set1To1Recipe(CONTENT_CRAFTITEM_LEATHER_RED,i);
	crafting::set1To1Recipe(CONTENT_CRAFTITEM_LEATHER_YELLOW,i);
	crafting::set1To1Recipe(CONTENT_CRAFTITEM_LEATHER_BLACK,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_GOLD_MEDALLION;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_MEDALLION;
	f->texture = "clothes_medallion_gold.png";
	f->overlay_texture = "clothes_player_medallion_gold.png";
	f->description = wgettext("Gold Medallion");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CLOTHESITEM_LEATHER_NECKLACE,CONTENT_CRAFTITEM_GOLD_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COPPER_MEDALLION;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_MEDALLION;
	f->texture = "clothes_medallion_copper.png";
	f->overlay_texture = "clothes_player_medallion_copper.png";
	f->description = wgettext("Copper Medallion");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CLOTHESITEM_LEATHER_NECKLACE,CONTENT_CRAFTITEM_COPPER_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_SILVER_MEDALLION;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_MEDALLION;
	f->texture = "clothes_medallion_silver.png";
	f->overlay_texture = "clothes_player_medallion_silver.png";
	f->description = wgettext("Silver Medallion");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CLOTHESITEM_LEATHER_NECKLACE,CONTENT_CRAFTITEM_SILVER_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_TIN_MEDALLION;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_MEDALLION;
	f->texture = "clothes_medallion_tin.png";
	f->overlay_texture = "clothes_player_medallion_tin.png";
	f->description = wgettext("Tin Medallion");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CLOTHESITEM_LEATHER_NECKLACE,CONTENT_CRAFTITEM_TIN_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_IRON_MEDALLION;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_MEDALLION;
	f->texture = "clothes_medallion_iron.png";
	f->overlay_texture = "clothes_player_medallion_iron.png";
	f->description = wgettext("Iron Medallion");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CLOTHESITEM_LEATHER_NECKLACE,CONTENT_CRAFTITEM_STEEL_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_QUARTZ_MEDALLION;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_MEDALLION;
	f->texture = "clothes_medallion_quartz.png";
	f->overlay_texture = "clothes_player_medallion_quartz.png";
	f->description = wgettext("Quartz Medallion");
	f->armour = 0.0;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::set1over1Recipe(CONTENT_CLOTHESITEM_LEATHER_NECKLACE,CONTENT_CRAFTITEM_QUARTZ,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	// armour
	i = CONTENT_CLOTHESITEM_STEEL_HELMET;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_steel.png";
	f->overlay_texture = "clothes_player_helmet_steel.png";
	f->description = wgettext("Steel Helmet");
	f->armour = 0.2;
	f->warmth = 0.0;
	f->vacuum = 0.5;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_STEEL_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_STEEL_SHIRT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_shirt_steel.png";
	f->overlay_texture = "clothes_player_shirt_steel.png";
	f->description = wgettext("Steel Chest Armour");
	f->armour = 0.3;
	f->warmth = 0.0;
	f->vacuum = 0.05;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_STEEL_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_STEEL_PANTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_steel.png";
	f->overlay_texture = "clothes_player_pants_steel.png";
	f->description = wgettext("Steel Pants");
	f->armour = 0.3;
	f->warmth = 0.0;
	f->vacuum = 0.5;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_STEEL_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_STEEL_BOOTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_steel.png";
	f->overlay_texture = "clothes_player_boots_steel.png";
	f->description = wgettext("Steel Boots");
	f->armour = 0.2;
	f->warmth = 0.0;
	f->vacuum = 0.05;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_STEEL_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COPPER_HELMET;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_HAT;
	f->texture = "clothes_helmet_copper.png";
	f->overlay_texture = "clothes_player_helmet_copper.png";
	f->description = wgettext("Copper Helmet");
	f->armour = 0.15;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setHatRecipe(CONTENT_CRAFTITEM_COPPER_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COPPER_SHIRT;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_JACKET;
	f->texture = "clothes_shirt_copper.png";
	f->overlay_texture = "clothes_player_shirt_copper.png";
	f->description = wgettext("Copper Chest Armour");
	f->armour = 0.20;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setShirtRecipe(CONTENT_CRAFTITEM_COPPER_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COPPER_PANTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_PANTS;
	f->texture = "clothes_pants_copper.png";
	f->overlay_texture = "clothes_player_pants_copper.png";
	f->description = wgettext("Copper Pants");
	f->armour = 0.20;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setPantsRecipe(CONTENT_CRAFTITEM_COPPER_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);

	i = CONTENT_CLOTHESITEM_COPPER_BOOTS;
	f = &g_content_clothesitem_features[i];
	f->content = i;
	f->type = CT_BOOTS;
	f->texture = "clothes_boots_copper.png";
	f->overlay_texture = "clothes_player_boots_copper.png";
	f->description = wgettext("Copper Boots");
	f->armour = 0.15;
	f->warmth = 0.0;
	f->vacuum = 0.0;
	crafting::setBootsRecipe(CONTENT_CRAFTITEM_COPPER_INGOT,i);
	lists::add("craftguide",i);
	lists::add("creative",i);
}
