#ifndef CONTENT_NODEBOX_HEADER
#define CONTENT_NODEBOX_HEADER

struct ContentFeatures;

void content_nodebox_stair(ContentFeatures *f);
void content_nodebox_stairud(ContentFeatures *f);
void content_nodebox_slab(ContentFeatures *f);
void content_nodebox_slabud(ContentFeatures *f);
void content_nodebox_door(ContentFeatures *f);
void content_nodebox_doorw(ContentFeatures *f);
void content_nodebox_doorol(ContentFeatures *f);
void content_nodebox_doorwol(ContentFeatures *f);
void content_nodebox_dooror(ContentFeatures *f);
void content_nodebox_doorwor(ContentFeatures *f);
void content_nodebox_hatch(ContentFeatures *f);
void content_nodebox_hatchw(ContentFeatures *f);
void content_nodebox_hatcho(ContentFeatures *f);
void content_nodebox_hatchwo(ContentFeatures *f);
void content_nodebox_gate(ContentFeatures *f);
void content_nodebox_gateo(ContentFeatures *f);
void content_nodebox_carpet(ContentFeatures *f);
void content_nodebox_bed_head(ContentFeatures *f);
void content_nodebox_bed_foot(ContentFeatures *f);
void content_nodebox_plant_1(ContentFeatures *f);
void content_nodebox_plant_2(ContentFeatures *f);
void content_nodebox_plant_3(ContentFeatures *f);
void content_nodebox_guide(ContentFeatures *f);
void content_nodebox_painting(ContentFeatures *f);
void content_nodebox_book(ContentFeatures *f);
void content_nodebox_pie(ContentFeatures *f);
void content_nodebox_pie_3(ContentFeatures *f);
void content_nodebox_pie_2(ContentFeatures *f);
void content_nodebox_pie_1(ContentFeatures *f);
void content_nodebox_sign(ContentFeatures *f);
void content_nodebox_sign_ud(ContentFeatures *f);
void content_nodebox_sign_wall(ContentFeatures *f);
void content_nodebox_jackolantern(ContentFeatures *f);
void content_nodebox_roofcollide(ContentFeatures *f);
void content_nodebox_bookshelf(ContentFeatures *f);
void content_nodebox_couch_centre(ContentFeatures *f);
void content_nodebox_couch_left(ContentFeatures *f);
void content_nodebox_couch_right(ContentFeatures *f);
void content_nodebox_couch_chair(ContentFeatures *f);
void content_nodebox_couch_inner(ContentFeatures *f);
void content_nodebox_couch_outer(ContentFeatures *f);
void content_nodebox_knob(ContentFeatures *f);
void content_nodebox_battery(ContentFeatures *f);
void content_nodebox_switch(ContentFeatures *f);
void content_nodebox_button(ContentFeatures *f);
void content_nodebox_logicgate(ContentFeatures *f);
void content_nodebox_piston(ContentFeatures *f);
void content_nodebox_pistonarm(ContentFeatures *f);
void content_nodebox_piston_up(ContentFeatures *f);
void content_nodebox_pistonarm_up(ContentFeatures *f);
void content_nodebox_piston_down(ContentFeatures *f);
void content_nodebox_pistonarm_down(ContentFeatures *f);
void content_nodebox_waterwheel(ContentFeatures *f);
void content_nodebox_clock(ContentFeatures *f);
void content_nodebox_fence_inv(ContentFeatures *f);
void content_nodebox_fence(ContentFeatures *f);
void content_nodebox_wall_inv(ContentFeatures *f);
void content_nodebox_wall(ContentFeatures *f);
void content_nodebox_bars(ContentFeatures *f);
void content_nodebox_youngtree(ContentFeatures *f);
void content_nodebox_flag(ContentFeatures *f);
void content_nodebox_flower_pot(ContentFeatures *f);
void content_nodebox_parcel(ContentFeatures *f);
void content_nodebox_cauldron(ContentFeatures *f);
void content_nodebox_forge(ContentFeatures *f);
void content_nodebox_furnace(ContentFeatures *f);
void content_nodebox_lockedfurnace(ContentFeatures *f);
void content_nodebox_incinerator(ContentFeatures *f);
void content_nodebox_rock(ContentFeatures *f);

#endif
